[package]
name = "Rust_Projects"
version = "0.1.0"
authors = ["debasish"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
